services:
  db:
    image: pgvector/pgvector:pg18-trixie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vector_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vector_db
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  migrate:
    build: .
    command: alembic -c db/alembic.ini upgrade head
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/vector_db
    volumes:
      - .:/backend
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    command: fastapi dev api/main.py --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      AWS_PROFILE: default
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/vector_db
    volumes:
      - .:/backend
      - ~/.aws:/root/.aws
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started

  worker:
    build: .
    command: python -m workers.main
    environment:
      AWS_PROFILE: default
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/vector_db
    volumes:
      - .:/backend
      - ~/.aws:/root/.aws
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    develop:
      watch:
        - path: ./workers
          action: restart

        - path: ./shared
          action: restart

        - path: ./db
          action: restart

volumes:
  redis_data:
  db_data:
